package adc.tutorial.elasticsearch.services

import java.io.Writer

import adc.tutorial.elasticsearch.model.Movie
import akka.actor.ActorSystem
import akka.stream.scaladsl._
import akka.stream.{ClosedShape, Graph, ThrottleMode}
import akka.{Done, NotUsed}
import play.api.libs.json.{JsValue, Json}
import play.api.libs.ws.StandaloneWSClient

import scala.concurrent.duration._
import scala.concurrent.{ExecutionContext, Future}
import scala.io.{BufferedSource, Source => IOSource}
import scala.language.postfixOps

/**
  * Generates move data
  * <p>
  *    This data is generated from the <tt>https://themoviedb.org</tt>
  * </p>
  */
class DataSourceService(url: String, api_key: String, wsClient: StandaloneWSClient) {
  import DataSourceService._
  import GraphDSL.Implicits._

  /**
    * create a source that reads ids from the file and calls the <tt>the moviedb.org</tt> to get the corresponding json
    * @param offset where to start reading in the file <tt>movieIdFileName</tt>
    * @param count how many movies to retrieve from the web
    * @param actorSystem used for stream
    * @return source of movie data as json
    */
  def fromWeb(offset: Int, count: Int)(implicit actorSystem: ActorSystem): Source[JsValue, NotUsed] =
    Source(ids(offset, count))
      .throttle(elements=35, per=10 seconds, maximumBurst=1, mode=ThrottleMode.shaping) // rate limits imposed by themoviedb.org
      .mapAsync(1)(id => webCall(id))

  /**
    * create a source that reads json from a file, rather than from the web
    * @param offset where to start reading in the file (conf/movie.json)
    * @param count how many movies to read
    * @return source of movie data as json
    */
  def fromFile(offset: Int, count: Int): Source[JsValue, NotUsed] =
    Source
      .fromIterator[String](() => fileCall(offset, count))
      .map(s => Json.parse(s))

  def moviesFromFile(source: IOSource, offset: Int, count: Int): Iterator[Movie] = {
      source.getLines()
      .slice(offset, offset+count)
      .map[JsValue](s => Json.parse(s))
      .map[Movie](j => {
          Movie.fromMovieDbJson(j)
      })
  }
  def fromIterator(count: Int): Source[JsValue, NotUsed] = Source.fromIterator( () => fixedList.take(count).map(Json.parse(_)).iterator )

  def getLines(offset: Int, count: Int): Iterator[String] = {
    IOSource.fromFile(movieJsonFileName).getLines()
  }
  /**
    * get a list of movie ids
    * @param offset where to start reading in the file <tt>movieIdFileName</tt>
    * @param count how many movies
    * @return list of movie ids
    */
  protected[services] def ids(offset: Int, count: Int): List[Int] = {
    val source = IOSource.fromFile(movieIdFileName)
    val list = source.getLines().slice(offset, offset+count).map(_.toInt).toList
    source.close()
    list
  }

  /**
    * read a string representing movie json data from the <tt>
    * @param offset where in the file to start reading
    * @param count how many movies to read
    * @return
    */
  protected[services] def fileCall(offset: Int, count:Int): Iterator[String] = {
    IOSource.fromFile(movieJsonFileName)
     .getLines()
      .slice(offset, offset+count)
  }

  /**
    * get the movie data as json based on the id from <tt>themoviedb.org</tt>
    * @param id id of the movie
    * @param actorSystem system for http calls
    * @return movie data as json
    */
  protected[services] def webCall(id: Int)(implicit actorSystem: ActorSystem): Future[JsValue] = {
    implicit val ec: ExecutionContext = actorSystem.dispatcher
    wsClient.url(s"$url/$id?api_key=$api_key").get().map {response =>
      response.status match {
        case 200 => Json.parse(response.body[String])
        case x => Json.obj("status" -> x)
      }
    }
  }

  /**
    * create a graph that reads movie json data from the source and prints the id's to standard out
    * @param source source of movie json data
    * @param actorSystem for stream
    * @return
    */
  protected[services] def printGraph(source: Source[JsValue, NotUsed])(implicit actorSystem: ActorSystem): Graph[ClosedShape, Future[Done]] = {
    GraphDSL.create(Sink.ignore) { implicit builder: GraphDSL.Builder[Future[Done]] => s =>
        val print: Flow[JsValue, Unit, NotUsed] = Flow[JsValue].map(jsv => {
          try {
            val id = jsv("id")
            println(s"id: $id")
          } catch {
            case _: Throwable => println(s"no id in ${Json.prettyPrint(jsv)}")
          }
        })
        source ~> print ~> s
        ClosedShape
    }
  }
}

object DataSourceService {
  val movieIdFileName = "conf/movie.ids"
  val movieJsonFileName = "conf/movie.json"
  val maxWeb = 322311
  val maxFile = 6000

  val fixedList: List[String] = List(
                                      """ {"adult":false,"backdrop_path":"/z2QUexmccqrvw1kDMw3R8TxAh5E.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":18,"name":"Drama"},{"id":80,"name":"Crime"}],"homepage":"","id":2,"imdb_id":"tt0094675","original_language":"fi","original_title":"Ariel","overview":"Taisto Kasurinen is a Finnish coal miner whose father has just committed suicide and who is framed for a crime he did not commit. In jail, he starts to dream about leaving the country and starting a new life. He escapes from prison but things don't go as planned...","popularity":1.145042,"poster_path":"/gZCJZOn4l0Zj5hAxsMbxoS6CL0u.jpg","production_companies":[{"name":"Villealfa Filmproduction Oy","id":2303},{"name":"Finnish Film Foundation","id":2396}],"production_countries":[{"iso_3166_1":"FI","name":"Finland"}],"release_date":"1988-10-21","revenue":0,"runtime":69,"spoken_languages":[{"iso_639_1":"fi","name":"suomi"},{"iso_639_1":"de","name":"Deutsch"}],"status":"Released","tagline":"","title":"Ariel","video":false,"vote_average":7.1,"vote_count":40} """
                                      ,"""  {"adult":false,"backdrop_path":"/6YjUX87VtIEuDzanBE6obVxE9V3.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":18,"name":"Drama"},{"id":35,"name":"Comedy"}],"homepage":"","id":3,"imdb_id":"tt0092149","original_language":"fi","original_title":"Varjoja paratiisissa","overview":"An episode in the life of Nikander, a garbage man, involving the death of a co-worker, an affair and much more.","popularity":0.416326,"poster_path":"/7ad4iku8cYBuB08g9yAU7tHJik5.jpg","production_companies":[{"name":"Villealfa Filmproduction Oy","id":2303}],"production_countries":[{"iso_3166_1":"FI","name":"Finland"}],"release_date":"1986-10-16","revenue":0,"runtime":76,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"fi","name":"suomi"},{"iso_639_1":"sv","name":"svenska"}],"status":"Released","tagline":"","title":"Shadows in Paradise","video":false,"vote_average":7,"vote_count":32} """
                                      ,"""  {"adult":false,"backdrop_path":"/3EqYpbGCE9S5GddU2K4cYzP5UmI.jpg","belongs_to_collection":null,"budget":4000000,"genres":[{"id":80,"name":"Crime"},{"id":35,"name":"Comedy"}],"homepage":"","id":5,"imdb_id":"tt0113101","original_language":"en","original_title":"Four Rooms","overview":"It's Ted the Bellhop's first night on the job...and the hotel's very unusual guests are about to place him in some outrageous predicaments. It seems that this evening's room service is serving up one unbelievable happening after another.","popularity":1.867424,"poster_path":"/eQs5hh9rxrk1m4xHsIz1w11Ngqb.jpg","production_companies":[{"name":"Miramax Films","id":14},{"name":"A Band Apart","id":59}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1995-12-25","revenue":4300000,"runtime":98,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Twelve outrageous guests. Four scandalous requests. And one lone bellhop, in his first day on the job, who's in for the wildest New year's Eve of his life.","title":"Four Rooms","video":false,"vote_average":6.5,"vote_count":485} """
                                      ,"""  {"adult":false,"backdrop_path":"/eXKgVIjLCFNpQkjVg1VpA8yM2GA.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":28,"name":"Action"},{"id":53,"name":"Thriller"},{"id":80,"name":"Crime"}],"homepage":"","id":6,"imdb_id":"tt0107286","original_language":"en","original_title":"Judgment Night","overview":"While racing to a boxing match, Frank, Mike, John and Rey get more than they bargained for. A wrong turn lands them directly in the path of Fallon, a vicious, wise-cracking drug lord. After accidentally witnessing Fallon murder a disloyal henchman, the four become his unwilling prey in a savage game of cat &amp; mouse as they are mercilessly stalked through the urban jungle in this taut suspense drama","popularity":1.356346,"poster_path":"/lNXmgUrP6h1nD53gkFh4WDzT6RZ.jpg","production_companies":[{"name":"Universal Pictures","id":33},{"name":"Largo Entertainment","id":1644},{"name":"JVC Entertainment Networks","id":4248}],"production_countries":[{"iso_3166_1":"JP","name":"Japan"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1993-10-15","revenue":12136938,"runtime":110,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Don't move. Don't whisper. Don't even breathe.","title":"Judgment Night","video":false,"vote_average":6.5,"vote_count":70} """
                                      ,"""  {"adult":false,"backdrop_path":"/udvB86uyzJ6P9vmB83WfrCbnmnI.jpg","belongs_to_collection":null,"budget":42000,"genres":[{"id":99,"name":"Documentary"}],"homepage":"http://www.lifeinloops.com","id":8,"imdb_id":"tt0825671","original_language":"en","original_title":"Life in Loops (A Megacities RMX)","overview":"Timo Novotny labels his new project an experimental music documentary film, in a remix of the celebrated film Megacities (1997), a visually refined essay on the hidden faces of several world \"megacities\" by leading Austrian documentarist Michael Glawogger. Novotny complements 30 % of material taken straight from the film (and re-edited) with 70 % as yet unseen footage in which he blends original shots unused by Glawogger with his own sequences (shot by Megacities cameraman Wolfgang Thaler) from Tokyo. Alongside the Japanese metropolis, Life in Loops takes us right into the atmosphere of Mexico City, New York, Moscow and Bombay. This electrifying combination of fascinating film images and an equally compelling soundtrack from Sofa Surfers sets us off on a stunning audiovisual adventure across the continents. The film also makes an original contribution to the discussion on new trends in documentary filmmaking. Written by KARLOVY VARY IFF 2006","popularity":0.015503,"poster_path":"/8YyIjOAxwzD3fZMdmJrfiApod4l.jpg","production_companies":[{"name":"inLoops","id":19123}],"production_countries":[{"iso_3166_1":"AT","name":"Austria"}],"release_date":"2006-01-01","revenue":0,"runtime":80,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"hi","name":"हिन्दी"},{"iso_639_1":"ja","name":"日本語"},{"iso_639_1":"ru","name":"Pусский"},{"iso_639_1":"es","name":"Español"}],"status":"Released","tagline":"A Megacities remix.","title":"Life in Loops (A Megacities RMX)","video":false,"vote_average":6.4,"vote_count":4} """
                                      ,"""  {"adult":false,"backdrop_path":"/4iJfYYoQzZcONB9hNzg0J0wWyPH.jpg","belongs_to_collection":{"id":10,"name":"Star Wars Collection","poster_path":"/ghd5zOQnDaDW1mxO7R5fXXpZMu.jpg","backdrop_path":"/d8duYyyC9J5T825Hg7grmaabfxQ.jpg"},"budget":11000000,"genres":[{"id":12,"name":"Adventure"},{"id":28,"name":"Action"},{"id":878,"name":"Science Fiction"}],"homepage":"http://www.starwars.com/films/star-wars-episode-iv-a-new-hope","id":11,"imdb_id":"tt0076759","original_language":"en","original_title":"Star Wars","overview":"Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.","popularity":9.987843,"poster_path":"/tvSlBzAdRE29bZe5yYWrJ2ds137.jpg","production_companies":[{"name":"Lucasfilm","id":1},{"name":"Twentieth Century Fox Film Corporation","id":306}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1977-05-25","revenue":775398007,"runtime":121,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"A long time ago in a galaxy far, far away...","title":"Star Wars","video":false,"vote_average":8,"vote_count":6171} """
                                      ,"""  {"adult":false,"backdrop_path":"/n2vIGWw4ezslXjlP0VNxkp9wqwU.jpg","belongs_to_collection":{"id":137697,"name":"Finding Nemo Collection","poster_path":"/xwggrEugjcJDuabIWvK2CpmK91z.jpg","backdrop_path":"/2hC8HHRUvwRljYKIcQDMyMbLlxz.jpg"},"budget":94000000,"genres":[{"id":16,"name":"Animation"},{"id":10751,"name":"Family"}],"homepage":"http://movies.disney.com/finding-nemo","id":12,"imdb_id":"tt0266543","original_language":"en","original_title":"Finding Nemo","overview":"Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.","popularity":9.209619999999999,"poster_path":"/syPWyeeqzTQIxjIUaIFI7d0TyEY.jpg","production_companies":[{"name":"Pixar Animation Studios","id":3}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2003-05-30","revenue":940335536,"runtime":100,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"There are 3.7 trillion fish in the ocean, they're looking for one.","title":"Finding Nemo","video":false,"vote_average":7.6,"vote_count":5535} """
                                      ,"""  {"adult":false,"backdrop_path":"/ctOEhQiFIHWkiaYp7b0ibSTe5IL.jpg","belongs_to_collection":null,"budget":55000000,"genres":[{"id":35,"name":"Comedy"},{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],"homepage":"","id":13,"imdb_id":"tt0109830","original_language":"en","original_title":"Forrest Gump","overview":"A man with a low IQ has accomplished great things in his life and been present during significant historic events - in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him. 'Forrest Gump' is the story of a man who rose above his challenges, and who proved that determination, courage, and love are more important than ability.","popularity":10.7281,"poster_path":"/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg","production_companies":[{"name":"Paramount Pictures","id":4}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1994-07-06","revenue":677945399,"runtime":142,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"The world will never be the same, once you've seen it through the eyes of Forrest Gump.","title":"Forrest Gump","video":false,"vote_average":8.199999999999999,"vote_count":7208} """
                                      ,"""  {"adult":false,"backdrop_path":"/z5J18ByLeOZ68iORfMXmxeFuwyL.jpg","belongs_to_collection":null,"budget":15000000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://www.dreamworks.com/ab/","id":14,"imdb_id":"tt0169547","original_language":"en","original_title":"American Beauty","overview":"Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.","popularity":8.433865000000001,"poster_path":"/or1MP8BZIAjqWYxPdPX724ydKar.jpg","production_companies":[{"name":"DreamWorks SKG","id":27},{"name":"Jinks/Cohen Company","id":2721}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1999-09-15","revenue":356296601,"runtime":122,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Look closer.","title":"American Beauty","video":false,"vote_average":7.9,"vote_count":3000} """
                                      ,"""  {"adult":false,"backdrop_path":"/xqDfLC7XbiaVN5XxZBWOJCX0hU7.jpg","belongs_to_collection":null,"budget":839727,"genres":[{"id":9648,"name":"Mystery"},{"id":18,"name":"Drama"}],"homepage":"","id":15,"imdb_id":"tt0033467","original_language":"en","original_title":"Citizen Kane","overview":"Newspaper magnate, Charles Foster Kane is taken from his mother as a boy and made the ward of a rich industrialist. As a result, every well-meaning, tyrannical or self-destructive move he makes for the rest of his life appears in some way to be a reaction to that deeply wounding event.","popularity":3.070541,"poster_path":"/n8wfFsQ5vtm6dM8vdgXb6OLv2GY.jpg","production_companies":[{"name":"RKO Radio Pictures","id":6},{"name":"Mercury Productions","id":11447}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1941-04-30","revenue":23217674,"runtime":119,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"It's Terrific!","title":"Citizen Kane","video":false,"vote_average":7.9,"vote_count":1111} """
                                      ,"""  {"adult":false,"backdrop_path":"/5k89pUmFMZ82yPiL7bqxaFiDqaa.jpg","belongs_to_collection":{"id":498,"name":"Heart of Gold Collection","poster_path":"/cwrmUIVzOuR9FdqKBfERkMHdde0.jpg","backdrop_path":"/293UTX2btTkblOL7WZF1Q7veIJm.jpg"},"budget":12800000,"genres":[{"id":18,"name":"Drama"},{"id":80,"name":"Crime"},{"id":10402,"name":"Music"}],"homepage":"","id":16,"imdb_id":"tt0168629","original_language":"en","original_title":"Dancer in the Dark","overview":"Selma, a Czech immigrant on the verge of blindness, struggles to make ends meet for herself and her son, who has inherited the same genetic disorder and will suffer the same fate without an expensive operation. When life gets too difficult, Selma learns to cope through her love of musicals, escaping life's troubles - even if just for a moment - by dreaming up little numbers to the rhythmic beats of her surroundings.","popularity":2.425581,"poster_path":"/7xizDTz4Yj4IYm2ud4f6EfEXe5H.jpg","production_companies":[{"name":"Fine Line Features","id":8},{"name":"Zentropa Entertainments","id":76},{"name":"Danmarks Radio (DR)","id":119},{"name":"SVT Drama","id":157},{"name":"Arte","id":201},{"name":"Memfis Film","id":321},{"name":"France 3 Cinéma","id":591},{"name":"Angel films","id":2996},{"name":"TV 1000","id":4524},{"name":"Canal+","id":5358},{"name":"Constantin Film Produktion","id":5755},{"name":"Yleisradio (YLE)","id":5975},{"name":"Arte France Cinéma","id":6916},{"name":"Westdeutscher Rundfunk (WDR)","id":7025},{"name":"Blind Spot Pictures Oy","id":7330},{"name":"Vrijzinnig Protestantse Radio Omroep (VPRO)","id":8659},{"name":"Film4","id":9349},{"name":"Liberator Productions","id":11239},{"name":"Icelandic Film","id":14937},{"name":"Film i Väst","id":17513},{"name":"Pain Unlimited GmbH Filmproduktion","id":30268},{"name":"Trust Film Svenska","id":53667},{"name":"Cinematograph A/S","id":53668},{"name":"What Else? B.V","id":53669},{"name":"Filmek A/S","id":53670},{"name":"Lantia Cinema & Audiovisivi","id":53671}],"production_countries":[{"iso_3166_1":"AR","name":"Argentina"},{"iso_3166_1":"DK","name":"Denmark"},{"iso_3166_1":"FI","name":"Finland"},{"iso_3166_1":"FR","name":"France"},{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"IS","name":"Iceland"},{"iso_3166_1":"IT","name":"Italy"},{"iso_3166_1":"NL","name":"Netherlands"},{"iso_3166_1":"NO","name":"Norway"},{"iso_3166_1":"SE","name":"Sweden"},{"iso_3166_1":"GB","name":"United Kingdom"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2000-05-17","revenue":40031879,"runtime":140,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"You don't need eyes to see.","title":"Dancer in the Dark","video":false,"vote_average":7.6,"vote_count":349} """
                                      ,"""  {"adult":false,"backdrop_path":"/pkCC3myn5QuoLzplTlvZLB0w2AU.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":27,"name":"Horror"},{"id":53,"name":"Thriller"},{"id":9648,"name":"Mystery"}],"homepage":"http://www.whatisannwyn.co.uk/","id":17,"imdb_id":"tt0411267","original_language":"en","original_title":"The Dark","overview":"Adèle and her daughter Sarah are traveling on the Welsh coastline to see her husband James when Sarah disappears. A different but similar looking girl appears who says she died in a past time. Adèle tries to discover what happened to her daughter as she is tormented by Celtic mythology from the past.","popularity":1.283559,"poster_path":"/8fzjzQhLXl1afshhsE5Y3MGuco4.jpg","production_companies":[{"name":"Constantin Film","id":47},{"name":"Impact Pictures","id":248},{"name":"Isle of Man Film","id":2268},{"name":"UK Film Council","id":2452}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"GB","name":"United Kingdom"}],"release_date":"2006-01-26","revenue":0,"runtime":87,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"cy","name":"Cymraeg"}],"status":"Released","tagline":"One of the living for one of the dead.","title":"The Dark","video":false,"vote_average":5.6,"vote_count":69} """
                                      ,"""  {"adult":false,"backdrop_path":"/sySVDnPmjJl82TgnTP4DTYgD6lY.jpg","belongs_to_collection":null,"budget":90000000,"genres":[{"id":12,"name":"Adventure"},{"id":14,"name":"Fantasy"},{"id":28,"name":"Action"},{"id":53,"name":"Thriller"},{"id":878,"name":"Science Fiction"}],"homepage":"","id":18,"imdb_id":"tt0119116","original_language":"en","original_title":"The Fifth Element","overview":"In 2257, a taxi driver is unintentionally given the task of saving a young girl who is part of the key that will ensure the survival of humanity.","popularity":7.78011,"poster_path":"/zaFa1NRZEnFgRTv5OVXkNIZO78O.jpg","production_companies":[{"name":"Columbia Pictures","id":5},{"name":"Gaumont","id":9}],"production_countries":[{"iso_3166_1":"FR","name":"France"}],"release_date":"1997-05-07","revenue":263920180,"runtime":126,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"sv","name":"svenska"},{"iso_639_1":"de","name":"Deutsch"}],"status":"Released","tagline":"There is no future without it.","title":"The Fifth Element","video":false,"vote_average":7.2,"vote_count":3633} """
                                      ,"""  {"adult":false,"backdrop_path":"/gmH0N0bdlYGN1EUr8U2cMQYyg78.jpg","belongs_to_collection":null,"budget":92620000,"genres":[{"id":18,"name":"Drama"},{"id":878,"name":"Science Fiction"}],"homepage":"","id":19,"imdb_id":"tt0017136","original_language":"de","original_title":"Metropolis","overview":"In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.","popularity":2.918401,"poster_path":"/qriaeUUwdmlgethK3aSAx68mG05.jpg","production_companies":[{"name":"Paramount Pictures","id":4},{"name":"Universum Film (UFA)","id":12372}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"}],"release_date":"1927-01-10","revenue":650422,"runtime":153,"spoken_languages":[{"iso_639_1":"xx","name":"No Language"}],"status":"Released","tagline":"There can be no understanding between the hands and the brain unless the heart acts as mediator.","title":"Metropolis","video":false,"vote_average":8,"vote_count":614} """
                                      ,"""  {"adult":false,"backdrop_path":"/caLMOD3ZJ3V7qjlxDXrzlJfBLgD.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],"homepage":"http://www.clubcultura.com/clubcine/clubcineastas/isabelcoixet/mividasinmi/index.htm","id":20,"imdb_id":"tt0314412","original_language":"en","original_title":"My Life Without Me","overview":"A Pedro Almodovar production in which a fatally ill mother with only two months to live creates a list of things she wants to do before she dies with out telling her family of her illness.","popularity":0.8784,"poster_path":"/7Unqm5LpQGBfrBgFN10OOOguO3O.jpg","production_companies":[{"name":"El Deseo","id":49},{"name":"Milestone Productions","id":77}],"production_countries":[{"iso_3166_1":"CA","name":"Canada"},{"iso_3166_1":"ES","name":"Spain"}],"release_date":"2003-03-07","revenue":9726954,"runtime":106,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"","title":"My Life Without Me","video":false,"vote_average":7.2,"vote_count":75} """
                                      ,"""  {"adult":false,"backdrop_path":"/8vtPfPla4biTyLu28SOc88XXG1f.jpg","belongs_to_collection":{"id":252313,"name":"The Endless Summer Collection","poster_path":"/zhG3P4ALlXxoFi0CGfcVsR3qmDL.jpg","backdrop_path":"/rbeqwDmy0yPMxBqA2ELvu08okcn.jpg"},"budget":0,"genres":[{"id":99,"name":"Documentary"}],"homepage":"","id":21,"imdb_id":"tt0060371","original_language":"en","original_title":"The Endless Summer","overview":"The Endless Summer, by Bruce Brown, is one of the first and most influential surf movies of all times. The film documents American surfers Mike Hynson and Robert August as they travel the world during California’s winter (which back in 1965 was off-season for surfing) in search of the perfect wave and an endless summer.","popularity":0.116135,"poster_path":"/jqsZQPxeMjcvVN5aFGgAk7qQodr.jpg","production_companies":[{"name":"Bruce Brown Films","id":13723}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1966-06-15","revenue":0,"runtime":95,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"","title":"The Endless Summer","video":false,"vote_average":7.8,"vote_count":20} """
                                      ,"""  {"adult":false,"backdrop_path":"/8AUQ7YlJJA9C8kWk8P4YNHIcFDE.jpg","belongs_to_collection":{"id":295,"name":"Pirates of the Caribbean Collection","poster_path":"/sfhT0AIeK3acITOvfTtS8DiU5pQ.jpg","backdrop_path":"/cnKAGbX1rDkAquF2V1wVkptHDJO.jpg"},"budget":140000000,"genres":[{"id":12,"name":"Adventure"},{"id":14,"name":"Fantasy"},{"id":28,"name":"Action"}],"homepage":"http://disney.go.com/disneyvideos/liveaction/pirates/main_site/main.html","id":22,"imdb_id":"tt0325980","original_language":"en","original_title":"Pirates of the Caribbean: The Curse of the Black Pearl","overview":"Jack Sparrow, a freewheeling 17th-century pirate who roams the Caribbean Sea, butts heads with a rival pirate bent on pillaging the village of Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her. But their seafaring mission is hardly simple.","popularity":28.875117,"poster_path":"/tkt9xR1kNX5R9rCebASKck44si2.jpg","production_companies":[{"name":"Walt Disney Pictures","id":2},{"name":"Jerry Bruckheimer Films","id":130}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2003-07-09","revenue":655011224,"runtime":143,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Prepare to be blown out of the water.","title":"Pirates of the Caribbean: The Curse of the Black Pearl","video":false,"vote_average":7.4,"vote_count":6381} """
                                      ,"""  {"adult":false,"backdrop_path":"/kkS8PKa8c134vXsj2fQkNqOaCXU.jpg","belongs_to_collection":{"id":2883,"name":"Kill Bill Collection","poster_path":"/tf1nUtw3LJGUGv1EFFi23iz6ngr.jpg","backdrop_path":"/oCLKNACMNrEf4T1EP6BpMXDl5m1.jpg"},"budget":30000000,"genres":[{"id":28,"name":"Action"},{"id":80,"name":"Crime"}],"homepage":"http://www.miramax.com/movie/kill-bill-volume-1/","id":24,"imdb_id":"tt0266697","original_language":"en","original_title":"Kill Bill: Vol. 1","overview":"An assassin is shot at the altar by her ruthless employer, Bill and other members of their assassination circle – but 'The Bride' lives to plot her vengeance. Setting out for some payback, she makes a death list and hunts down those who wronged her, saving Bill for last.","popularity":9.414023,"poster_path":"/97fNAi62HawGjWru7PvVmF7RAbU.jpg","production_companies":[{"name":"Miramax Films","id":14},{"name":"A Band Apart","id":59},{"name":"Super Cool ManChu","id":39121}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2003-10-10","revenue":180949000,"runtime":111,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"ja","name":"日本語"},{"iso_639_1":"fr","name":"Français"}],"status":"Released","tagline":"Go for the kill.","title":"Kill Bill: Vol. 1","video":false,"vote_average":7.7,"vote_count":4491} """
                                      ,"""  {"adult":false,"backdrop_path":"/shg7ZGAGVxhM9ZfOtV6bp93QZwt.jpg","belongs_to_collection":{"id":285564,"name":"Jarhead Collection","poster_path":"/aRFpBjCseFD6UmahAuLdqS7Or5q.jpg","backdrop_path":"/ifSnip5tvaHvxLPAyjkiihE6T2I.jpg"},"budget":72000000,"genres":[{"id":18,"name":"Drama"},{"id":10752,"name":"War"}],"homepage":"","id":25,"imdb_id":"tt0418763","original_language":"en","original_title":"Jarhead","overview":"Jarhead is a film about a US Marine Anthony Swofford’s experience in the Gulf War. After putting up with an arduous boot camp, Swafford and his unit are sent to the Persian Gulf where they are earger to fight but are forced to stay back from the action. Meanwhile Swofford gets news of his girlfriend is cheating on him. Desperately he wants to kill someone and finally put his training to use.","popularity":1.855009,"poster_path":"/iEYnXqUsfTaKwO1svSa39Ap07of.jpg","production_companies":[{"name":"Universal Pictures","id":33},{"name":"Neal Street Productions","id":1522},{"name":"Red Wagon Entertainment","id":14440},{"name":"Motion Picture KAPPA Produktionsgesellschaft","id":19934}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2005-11-04","revenue":96889998,"runtime":125,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"es","name":"Español"},{"iso_639_1":"ar","name":"العربية"},{"iso_639_1":"la","name":"Latin"}],"status":"Released","tagline":"Welcome to the suck.","title":"Jarhead","video":false,"vote_average":6.5,"vote_count":722} """
                                      ,"""  {"adult":false,"backdrop_path":"/osVUxR3HdccQG8yBKX3VWp8nVFv.jpg","belongs_to_collection":null,"budget":1400000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://www.walkonwatermovie.com","id":26,"imdb_id":"tt0352994","original_language":"en","original_title":"LaLehet Al HaMayim","overview":"Eyal, an Israeli Mossad agent, is given the mission to track down and kill the very old Alfred Himmelman, an ex-Nazi officer, who might still be alive. Pretending to be a tourist guide, he befriends his grandson Axel, in Israel to visit his sister Pia. The two men set out on a tour of the country during which, Axel challenges Eyal's values.","popularity":0.309932,"poster_path":"/5BH0k5pauAqywpr4NL9nKYcKC6O.jpg","production_companies":[{"name":"Lama Films","id":15},{"name":"United King Films","id":16}],"production_countries":[{"iso_3166_1":"IL","name":"Israel"},{"iso_3166_1":"SE","name":"Sweden"}],"release_date":"2004-02-05","revenue":0,"runtime":103,"spoken_languages":[{"iso_639_1":"ar","name":"العربية"},{"iso_639_1":"en","name":"English"},{"iso_639_1":"de","name":"Deutsch"},{"iso_639_1":"he","name":"עִבְרִית"},{"iso_639_1":"it","name":"Italiano"},{"iso_639_1":"tr","name":"Türkçe"}],"status":"Released","tagline":"He was trained to hate until he met the enemy.","title":"Walk on Water","video":false,"vote_average":6.4,"vote_count":18} """
                                      ,"""  {"adult":false,"backdrop_path":"/tie8vA3q3Q9BB5RlMlexRvv9xoh.jpg","belongs_to_collection":null,"budget":1000000,"genres":[{"id":18,"name":"Drama"},{"id":10402,"name":"Music"},{"id":10749,"name":"Romance"}],"homepage":"","id":27,"imdb_id":"tt0411705","original_language":"en","original_title":"9 Songs","overview":"Matt, a young glaciologist, soars across the vast, silent, icebound immensities of the South Pole as he recalls his love affair with Lisa. They meet at a mobbed rock concert in a vast music hall - London's Brixton Academy. They are in bed at night's end. Together, over a period of several months, they pursue a mutual sexual passion whose inevitable stages unfold in counterpoint to nine live-concert songs.","popularity":3.068388,"poster_path":"/bvGyYmmnQG5NPP7m2nuLhaiC8LH.jpg","production_companies":[{"name":"Revolution Films","id":163}],"production_countries":[{"iso_3166_1":"GB","name":"United Kingdom"}],"release_date":"2004-07-16","revenue":1574623,"runtime":66,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"2 lovers, one summer, and the 9 songs that defined them.","title":"9 Songs","video":false,"vote_average":5.1,"vote_count":95} """
                                      ,"""  {"adult":false,"backdrop_path":"/k91Dag8AZbhjIJqrtf7F1bQnGPg.jpg","belongs_to_collection":null,"budget":31500000,"genres":[{"id":18,"name":"Drama"},{"id":10752,"name":"War"}],"homepage":"http://www.apocalypsenow.com","id":28,"imdb_id":"tt0078788","original_language":"en","original_title":"Apocalypse Now","overview":"At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, \"does not exist, nor will it ever exist.\" His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.","popularity":5.010111,"poster_path":"/jcvJ2xcVWU9Wh0hZAxcs103s8nN.jpg","production_companies":[{"name":"United Artists","id":60},{"name":"Zoetrope Studios","id":26663}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1979-08-15","revenue":89460381,"runtime":153,"spoken_languages":[{"iso_639_1":"km","name":""},{"iso_639_1":"en","name":"English"},{"iso_639_1":"fr","name":"Français"},{"iso_639_1":"vi","name":"Tiếng Việt"}],"status":"Released","tagline":"This is the end...","title":"Apocalypse Now","video":false,"vote_average":8,"vote_count":1871} """
                                      ,"""  {"adult":false,"backdrop_path":"/8A11sHkxWPHtXM1H3jzuWZpAvg5.jpg","belongs_to_collection":{"id":139450,"name":"Memories Collection","poster_path":"/gJFRQeYxw96HJv4SBPLZfJVHKmG.jpg","backdrop_path":"/57PtyLQ1vVl5OcTO2vm0thO5JbQ.jpg"},"budget":0,"genres":[{"id":16,"name":"Animation"},{"id":878,"name":"Science Fiction"}],"homepage":"","id":30,"imdb_id":"tt1530535","original_language":"ja","original_title":"彼女の想いで","overview":"Koji Morimato’s animated science fiction short story about how the boarder between reality and illusion on a space station become blurry.","popularity":0.488066,"poster_path":"/1A59xquD5rZeQRgjMfI4qu1ZvcQ.jpg","production_companies":[{"name":"Studio 4°C","id":11671}],"production_countries":[{"iso_3166_1":"JP","name":"Japan"}],"release_date":"1995-12-23","revenue":0,"runtime":44,"spoken_languages":[{"iso_639_1":"ja","name":"日本語"}],"status":"Released","tagline":"","title":"Magnetic Rose","video":false,"vote_average":7.7,"vote_count":10} """
                                      ,"""  {"adult":false,"backdrop_path":"/limMzynPgBuDVKTSngwtNaWdVaZ.jpg","belongs_to_collection":{"id":139450,"name":"Memories Collection","poster_path":"/gJFRQeYxw96HJv4SBPLZfJVHKmG.jpg","backdrop_path":"/57PtyLQ1vVl5OcTO2vm0thO5JbQ.jpg"},"budget":0,"genres":[{"id":28,"name":"Action"},{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"}],"homepage":"","id":31,"imdb_id":"tt6266826","original_language":"ja","original_title":"最臭兵器","overview":"Tensai Okamura’s animated action packed short story with lots of humorous elements in which a person transforms into a weapon of mass destruction without themselves being aware.","popularity":1.020234,"poster_path":"/5LRT8RxXsEg7Ni0YCa2p6R9Ogn.jpg","production_companies":[{"name":"Studio 4°C","id":11671}],"production_countries":[{"iso_3166_1":"JP","name":"Japan"}],"release_date":"1995-12-23","revenue":0,"runtime":40,"spoken_languages":[{"iso_639_1":"ja","name":"日本語"}],"status":"Released","tagline":"","title":"Stink Bomb","video":false,"vote_average":5.3,"vote_count":3} """
                                      ,"""  {"adult":false,"backdrop_path":"/9FF31wgbyFM1zeBNsRzhjGHMMaS.jpg","belongs_to_collection":{"id":139450,"name":"Memories Collection","poster_path":"/gJFRQeYxw96HJv4SBPLZfJVHKmG.jpg","backdrop_path":"/57PtyLQ1vVl5OcTO2vm0thO5JbQ.jpg"},"budget":0,"genres":[{"id":16,"name":"Animation"},{"id":36,"name":"History"}],"homepage":"","id":32,"imdb_id":"tt6264824","original_language":"ja","original_title":"大砲の街","overview":"Otomo Katsuhiro’s short anime story","popularity":1.008227,"poster_path":"/oJdlkTtDvvpgagO2JWBBxGq5mMN.jpg","production_companies":[{"name":"Studio 4°C","id":11671}],"production_countries":[{"iso_3166_1":"JP","name":"Japan"}],"release_date":"1995-12-23","revenue":0,"runtime":21,"spoken_languages":[{"iso_639_1":"ja","name":"日本語"}],"status":"Released","tagline":"","title":"Cannon Fodder","video":false,"vote_average":5.3,"vote_count":3} """
                                      ,"""  {"adult":false,"backdrop_path":"/nKYH8DaWjKE3RhEyaa0Ue01kPCp.jpg","belongs_to_collection":null,"budget":14000000,"genres":[{"id":37,"name":"Western"}],"homepage":"","id":33,"imdb_id":"tt0105695","original_language":"en","original_title":"Unforgiven","overview":"William Munny is a retired, once-ruthless killer turned gentle widower and hog farmer. To help support his two motherless children, he accepts one last bounty-hunter mission to find the men who brutalized a prostitute. Joined by his former partner and a cocky greenhorn, he takes on a corrupt sheriff.","popularity":2.906688,"poster_path":"/km6qw4qUkHQRN5y2U1juM1WkBFh.jpg","production_companies":[{"name":"Malpaso Productions","id":171},{"name":"Warner Bros.","id":6194}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1992-08-07","revenue":159157447,"runtime":131,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Some legends will never be forgotten. Some wrongs can never be forgiven.","title":"Unforgiven","video":false,"vote_average":7.7,"vote_count":1037} """
                                      ,"""  {"adult":false,"backdrop_path":"/4RaoQCwliLvbokgpFzMXvSznC0h.jpg","belongs_to_collection":null,"budget":75000000,"genres":[{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":10751,"name":"Family"}],"homepage":"http://www.simpsonsmovie.com/","id":35,"imdb_id":"tt0462538","original_language":"en","original_title":"The Simpsons Movie","overview":"After Homer accidentally pollutes the town's water supply, Springfield is encased in a gigantic dome by the EPA and the Simpsons are declared fugitives.","popularity":5.210204,"poster_path":"/eCytnEriVur3rT47NWfkgPXD9qs.jpg","production_companies":[{"name":"Gracie Films","id":18},{"name":"Twentieth Century Fox Film Corporation","id":306}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2007-07-25","revenue":527068851,"runtime":87,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"See our family. And feel better about yours.","title":"The Simpsons Movie","video":false,"vote_average":6.9,"vote_count":2049} """
                                      ,"""  {"adult":false,"backdrop_path":"/1dXTsaFxHoF9cas08UjAqE8NqOW.jpg","belongs_to_collection":null,"budget":20000000,"genres":[{"id":878,"name":"Science Fiction"},{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],"homepage":"http://www.eternalsunshine.com","id":38,"imdb_id":"tt0338013","original_language":"en","original_title":"Eternal Sunshine of the Spotless Mind","overview":"Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.","popularity":5.804482,"poster_path":"/7y3eYvTsGjxPYDtSnumCLIMDkrV.jpg","production_companies":[{"name":"Anonymous Content","id":10039},{"name":"This Is That Productions","id":10059},{"name":"Focus Features","id":10146}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2004-03-19","revenue":72258126,"runtime":108,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"You can erase someone from your mind. Getting them out of your heart is another story.","title":"Eternal Sunshine of the Spotless Mind","video":false,"vote_average":7.9,"vote_count":3334} """
                                      ,"""  {"adult":false,"backdrop_path":"/AuXC0SsPZaAfddtSMnxSnbEeEjR.jpg","belongs_to_collection":{"id":387037,"name":"Death Trilogy","poster_path":"/qbH1mr0EKrbR9kHdp5R8XPKnoM7.jpg","backdrop_path":"/qW0hrd7AiHh76N10SAoHmtIGmii.jpg"},"budget":2000000,"genres":[{"id":18,"name":"Drama"},{"id":53,"name":"Thriller"}],"homepage":"","id":55,"imdb_id":"tt0245712","original_language":"es","original_title":"Amores perros","overview":"Three different people in Mexico City are catapulted into dramatic and unforeseen circumstances in the wake of a terrible car crash: a young punk stumbles into the sinister underground world of dog fighting; an injured supermodel's designer pooch disappears into the apartment's floorboards; and an ex-radical turned hit man rescues a gunshot Rotweiler.","popularity":2.810994,"poster_path":"/8gEXmIzw1tDnBfOaCFPimkNIkmm.jpg","production_companies":[{"name":"Altavista Films","id":5084},{"name":"Zeta Film","id":11230}],"production_countries":[{"iso_3166_1":"MX","name":"Mexico"}],"release_date":"2000-06-16","revenue":20908467,"runtime":154,"spoken_languages":[{"iso_639_1":"es","name":"Español"}],"status":"Released","tagline":"Love. Betrayal. Death.","title":"Amores perros","video":false,"vote_average":7.6,"vote_count":486} """
                                      ,"""  {"adult":false,"backdrop_path":"/hdHgIcljPHli4xaJGt0INz8Gn3J.jpg","belongs_to_collection":{"id":295,"name":"Pirates of the Caribbean Collection","poster_path":"/sfhT0AIeK3acITOvfTtS8DiU5pQ.jpg","backdrop_path":"/cnKAGbX1rDkAquF2V1wVkptHDJO.jpg"},"budget":200000000,"genres":[{"id":12,"name":"Adventure"},{"id":14,"name":"Fantasy"},{"id":28,"name":"Action"}],"homepage":"http://disney.go.com/disneypictures/pirates/","id":58,"imdb_id":"tt0383574","original_language":"en","original_title":"Pirates of the Caribbean: Dead Man's Chest","overview":"Captain Jack Sparrow works his way out of a blood debt with the ghostly Davey Jones, he also attempts to avoid eternal damnation.","popularity":10.505676,"poster_path":"/waFr5RVKaQ9dzOt3nQuIVB1FiPu.jpg","production_companies":[{"name":"Walt Disney Pictures","id":2},{"name":"Jerry Bruckheimer Films","id":130},{"name":"Second Mate Productions","id":19936}],"production_countries":[{"iso_3166_1":"JM","name":"Jamaica"},{"iso_3166_1":"US","name":"United States of America"},{"iso_3166_1":"BS","name":"Bahamas"},{"iso_3166_1":"DM","name":"Dominica"}],"release_date":"2006-06-20","revenue":1065659812,"runtime":151,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"tr","name":"Türkçe"},{"iso_639_1":"el","name":"ελληνικά"},{"iso_639_1":"zh","name":"普通话"}],"status":"Released","tagline":"Jack is back!","title":"Pirates of the Caribbean: Dead Man's Chest","video":false,"vote_average":6.9,"vote_count":4799} """
                                      ,"""  {"adult":false,"backdrop_path":"/aBjvBbQWrR5gZbxS4WMSaT1XlZL.jpg","belongs_to_collection":null,"budget":32000000,"genres":[{"id":18,"name":"Drama"},{"id":53,"name":"Thriller"},{"id":80,"name":"Crime"}],"homepage":"","id":59,"imdb_id":"tt0399146","original_language":"en","original_title":"A History of Violence","overview":"An average family is thrust into the spotlight after the father commits a seemingly self-defense murder at his diner.","popularity":1.648787,"poster_path":"/mz1qCHXxTUJm2AqOdW3IIpwYdo3.jpg","production_companies":[{"name":"New Line Cinema","id":12},{"name":"DC Comics","id":429},{"name":"BenderSpink","id":6363}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2005-09-23","revenue":60740827,"runtime":96,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Tom Stall had the perfect life... until he became a hero.","title":"A History of Violence","video":false,"vote_average":6.9,"vote_count":781} """
                                      ,"""  {"adult":false,"backdrop_path":"/pckdZ29bHj11hBsV3SbVVfmCB6C.jpg","belongs_to_collection":{"id":4438,"name":"The Space Odyssey Series","poster_path":"/i1WdRtc6aObiwGz5NU8WWPW3r1N.jpg","backdrop_path":"/15FumSExI9SRoL7QJWZAsA0b10c.jpg"},"budget":10500000,"genres":[{"id":878,"name":"Science Fiction"},{"id":9648,"name":"Mystery"},{"id":12,"name":"Adventure"}],"homepage":"","id":62,"imdb_id":"tt0062622","original_language":"en","original_title":"2001: A Space Odyssey","overview":"Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world's most advanced super computer.","popularity":6.776441,"poster_path":"/90T7b2LIrL07ndYQBmSm09yqVEH.jpg","production_companies":[{"name":"Stanley Kubrick Productions","id":385},{"name":"Metro-Goldwyn-Mayer (MGM)","id":8411}],"production_countries":[{"iso_3166_1":"GB","name":"United Kingdom"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1968-04-05","revenue":68700000,"runtime":149,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"ru","name":"Pусский"}],"status":"Released","tagline":"An epic drama of adventure and exploration","title":"2001: A Space Odyssey","video":false,"vote_average":7.8,"vote_count":2751} """
                                      ,"""  {"adult":false,"backdrop_path":"/6KXbhaxkgExC5EdDqAzRinhmoZ8.jpg","belongs_to_collection":null,"budget":29500000,"genres":[{"id":878,"name":"Science Fiction"},{"id":53,"name":"Thriller"},{"id":9648,"name":"Mystery"}],"homepage":"","id":63,"imdb_id":"tt0114746","original_language":"en","original_title":"Twelve Monkeys","overview":"In the year 2035, convict James Cole reluctantly volunteers to be sent back in time to discover the origin of a deadly virus that wiped out nearly all of the earth's population and forced the survivors into underground communities. But when Cole is mistakenly sent to 1990 instead of 1996, he's arrested and locked up in a mental hospital. There he meets psychiatrist Dr. Kathryn Railly, and patient Jeffrey Goines, the son of a famous virus expert, who may hold the key to the mysterious rogue group, the Army of the 12 Monkeys, thought to be responsible for unleashing the killer disease.","popularity":4.272783,"poster_path":"/6Sj9wDu3YugthXsU0Vry5XFAZGg.jpg","production_companies":[{"name":"Universal Pictures","id":33},{"name":"Atlas Entertainment","id":507},{"name":"Classico","id":17031}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1995-12-29","revenue":168840000,"runtime":129,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"fr","name":"Français"}],"status":"Released","tagline":"The future is history.","title":"Twelve Monkeys","video":false,"vote_average":7.4,"vote_count":2229} """
                                      ,"""  {"adult":false,"backdrop_path":"/3QFJkOSvFOYs8kUhXfJ8nE4UBU6.jpg","belongs_to_collection":null,"budget":9285469,"genres":[{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],"homepage":"","id":64,"imdb_id":"tt0287467","original_language":"es","original_title":"Hable con Ella","overview":"Two men share an odd friendship while they care for two women who are both in deep comas.","popularity":1.393083,"poster_path":"/klsBB1YEGRyC7YjiLYCKIqkU6pY.jpg","production_companies":[{"name":"Vía Digital","id":357},{"name":"Good Machine","id":10565},{"name":"El Deseo S.A.","id":11736},{"name":"Antena 3 Televisión","id":11737}],"production_countries":[{"iso_3166_1":"ES","name":"Spain"}],"release_date":"2002-03-14","revenue":51001550,"runtime":112,"spoken_languages":[{"iso_639_1":"es","name":"Español"}],"status":"Released","tagline":"","title":"Talk to Her","video":false,"vote_average":7.4,"vote_count":242} """
                                      ,"""  {"adult":false,"backdrop_path":"/v8mJvyNO86mcmY00FlxxRcOoDJy.jpg","belongs_to_collection":null,"budget":41000000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://movies.uip.de/8mile/","id":65,"imdb_id":"tt0298203","original_language":"en","original_title":"8 Mile","overview":"The setting is Detroit in 1995. The city is divided by 8 Mile, a road that splits the town in half along racial lines. A young white rapper, Jimmy \"B-Rabbit\" Smith Jr summons strength within himself to cross over these arbitrary boundaries to fulfill his dream of success in hip hop. With future and the three one third all he has to do is not choke.","popularity":2.695898,"poster_path":"/dXzTrKwpbLpCqn8O70FUUhNbYQT.jpg","production_companies":[{"name":"Imagine Entertainment","id":23},{"name":"Mikona Productions GmbH & Co. KG","id":24}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2002-11-08","revenue":215000000,"runtime":110,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Every moment is another chance.","title":"8 Mile","video":false,"vote_average":6.8,"vote_count":1490} """
                                      ,"""  {"adult":false,"backdrop_path":"/zDSAJ8xpbq1jekZOT2DL9yasMEv.jpg","belongs_to_collection":null,"budget":50000000,"genres":[{"id":80,"name":"Crime"},{"id":18,"name":"Drama"},{"id":53,"name":"Thriller"}],"homepage":"","id":66,"imdb_id":"tt0118548","original_language":"en","original_title":"Absolute Power","overview":"A master thief coincidentally is robbing a house where a murder in which the President of The United States is involved occurs in front of his eyes. He is forced to run yet may hold evidence that could convict the President. A political thriller from and starring Clint Eastwood and based on a novel by David Baldacci.","popularity":1.939811,"poster_path":"/oJQdp09Oc51DkArsMDvgDLdWiDu.jpg","production_companies":[{"name":"Columbia Pictures","id":5},{"name":"Castle Rock Entertainment","id":97},{"name":"Malpaso Productions","id":171}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1997-02-14","revenue":50068310,"runtime":121,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"es","name":"Español"}],"status":"Released","tagline":"Corrupts Absolutely.","title":"Absolute Power","video":false,"vote_average":6.4,"vote_count":204} """
                                      ,"""  {"adult":false,"backdrop_path":"/lz1iJlKRBMtE6uHauUneX7THa0c.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":53,"name":"Thriller"},{"id":80,"name":"Crime"},{"id":18,"name":"Drama"}],"homepage":"http://wip.warnerbros.com/paradisenow/","id":67,"imdb_id":"tt0445620","original_language":"en","original_title":"Paradise Now","overview":"Paradise Now is filmed from the perspective of two Palestinian men who are preparing to perform a suicide attack in Israel. This is the first film to deal with the subject of suicide bombers.","popularity":0.806097,"poster_path":"/qWZkYa8VdcDZk8uzRB2PfhpM9IL.jpg","production_companies":[{"name":"Lama Films","id":15},{"name":"Augustus Film","id":89},{"name":"Lama Productions","id":91},{"name":"Lumer Films","id":93},{"name":"Hazazah Film","id":95},{"name":"Filmstiftung Nordrhein-Westfalen","id":315},{"name":"Razor Film Produktion GmbH","id":703},{"name":"Eurimages","id":850},{"name":"Nederlands Fonds voor de Film","id":4508},{"name":"Arte France Cinéma","id":6916},{"name":"Medienboard Berlin-Brandenburg","id":7307}],"production_countries":[{"iso_3166_1":"FR","name":"France"},{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"IL","name":"Israel"},{"iso_3166_1":"NL","name":"Netherlands"},{"iso_3166_1":"PS","name":"Palestinian Territory"}],"release_date":"2005-02-14","revenue":3357075,"runtime":90,"spoken_languages":[{"iso_639_1":"ar","name":"العربية"},{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"From the most unexpected place, come a  new call for peace.","title":"Paradise Now","video":false,"vote_average":6.9,"vote_count":60} """
                                      ,"""  {"adult":false,"backdrop_path":"/pVlZBKp8v3Jzd0ahPmrBGlbeQ2s.jpg","belongs_to_collection":null,"budget":15000000,"genres":[{"id":35,"name":"Comedy"},{"id":878,"name":"Science Fiction"}],"homepage":"","id":68,"imdb_id":"tt0088846","original_language":"en","original_title":"Brazil","overview":"Low-level bureaucrat Sam Lowry escapes the monotony of his day-to-day life through a recurring daydream of himself as a virtuous hero saving a beautiful damsel. Investigating a case that led to the wrongful arrest and eventual death of an innocent man instead of wanted terrorist Harry Tuttle, he meets the woman from his daydream, and in trying to help her gets caught in a web of mistaken identities, mindless bureaucracy and lies.","popularity":4.670229,"poster_path":"/55Vfc1beLn3pJF4Lw83TRKHenK6.jpg","production_companies":[{"name":"Embassy International Pictures","id":10214}],"production_countries":[{"iso_3166_1":"GB","name":"United Kingdom"}],"release_date":"1985-02-20","revenue":0,"runtime":132,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"It's only a state of mind.","title":"Brazil","video":false,"vote_average":7.6,"vote_count":800} """
                                      ,"""  {"adult":false,"backdrop_path":"/oT79THuFrcBzrhlf4fiCddwZBCQ.jpg","belongs_to_collection":null,"budget":28000000,"genres":[{"id":18,"name":"Drama"},{"id":10402,"name":"Music"},{"id":10749,"name":"Romance"}],"homepage":"","id":69,"imdb_id":"tt0358273","original_language":"en","original_title":"Walk the Line","overview":"A chronicle of country music legend Johnny Cash's life, from his early days on an Arkansas cotton farm to his rise to fame with Sun Records in Memphis, where he recorded alongside Elvis Presley, Jerry Lee Lewis and Carl Perkins.","popularity":1.264743,"poster_path":"/wdxL3Zyh3O5MIbmsSiZEevJAjtQ.jpg","production_companies":[{"name":"Tree Line Films","id":84},{"name":"Konrad Pictures","id":85},{"name":"Catfish Productions","id":86},{"name":"Fox 2000 Pictures","id":711},{"name":"Mars Media Beteiligungs","id":6402}],"production_countries":[{"iso_3166_1":"DE","name":"Germany"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2005-09-13","revenue":186438883,"runtime":136,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"ru","name":"Pусский"}],"status":"Released","tagline":"Love is a burning thing.","title":"Walk the Line","video":false,"vote_average":7.3,"vote_count":675} """
                                      ,"""  {"adult":false,"backdrop_path":"/7nGW4MhYQ7sJfp482XkrgqPYQ2S.jpg","belongs_to_collection":null,"budget":30000000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://www.milliondollarbaby-derfilm.de/","id":70,"imdb_id":"tt0405159","original_language":"en","original_title":"Million Dollar Baby","overview":"Despondent over a painful estrangement from his daughter, trainer Frankie Dunn isn't prepared for boxer Maggie Fitzgerald to enter his life. But Maggie's determined to go pro and to convince Dunn and his cohort to help her.","popularity":5.636283,"poster_path":"/h4VZKi2Jt4VoBYJmtC4c3bO8KqM.jpg","production_companies":[{"name":"Lakeshore Entertainment","id":126},{"name":"Malpaso Productions","id":171},{"name":"Epsilon Motion Pictures","id":1171},{"name":"Warner Bros.","id":6194},{"name":"Albert S. Ruddy Productions","id":16311}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2004-12-15","revenue":216763646,"runtime":132,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"ga","name":"Gaeilge"}],"status":"Released","tagline":"Beyond his silence, there is a past. Beyond her dreams, there is a feeling. Beyond hope, there is a memory. Beyond their journey, there is a love.","title":"Million Dollar Baby","video":false,"vote_average":7.7,"vote_count":2192} """
                                      ,"""  {"adult":false,"backdrop_path":"/vlnhKUvu335ZM8wSD27MaFHpNu2.jpg","belongs_to_collection":null,"budget":5000000,"genres":[{"id":18,"name":"Drama"},{"id":35,"name":"Comedy"},{"id":10402,"name":"Music"}],"homepage":"","id":71,"imdb_id":"tt0249462","original_language":"en","original_title":"Billy Elliot","overview":"Set against the background of the 1984 Miner's Strike, Billy Elliot is an 11 year old boy who stumbles out of the boxing ring and onto the ballet floor. He faces many trials and triumphs as he strives to conquer his family's set ways, inner conflict, and standing on his toes!","popularity":1.257325,"poster_path":"/6VaP1H3MOW5jdkWqS5Q1NapCOS6.jpg","production_companies":[{"name":"BBC Films","id":288},{"name":"Tiger Aspect Productions","id":686},{"name":"StudioCanal","id":694},{"name":"Arts Council of England","id":718},{"name":"Working Title Films","id":10163},{"name":"WT2 Productions","id":10462}],"production_countries":[{"iso_3166_1":"FR","name":"France"},{"iso_3166_1":"GB","name":"United Kingdom"}],"release_date":"2000-05-18","revenue":110000000,"runtime":110,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Inside every one of us is a special talent waiting to come out. The trick is finding it.","title":"Billy Elliot","video":false,"vote_average":7.4,"vote_count":657} """
                                      ,"""  {"adult":false,"backdrop_path":"/i9A0UMFg1hI2kLyCCwnmSbpT2cd.jpg","belongs_to_collection":null,"budget":20000000,"genres":[{"id":18,"name":"Drama"}],"homepage":"http://www.historyx.com/","id":73,"imdb_id":"tt0120586","original_language":"en","original_title":"American History X","overview":"Derek Vineyard is paroled after serving 3 years in prison for killing two thugs who tried to break into/steal his truck. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.","popularity":5.657687,"poster_path":"/fXepRAYOx1qC3wju7XdDGx60775.jpg","production_companies":[{"name":"New Line Cinema","id":12},{"name":"The Turman-Morrissey Company","id":924},{"name":"Savoy Pictures","id":11308}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1998-10-30","revenue":23875127,"runtime":119,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Some Legacies Must End.","title":"American History X","video":false,"vote_average":8.1,"vote_count":2751} """
                                      ,"""  {"adult":false,"backdrop_path":"/bwTb66gicrB7HbkogwNs9V37Ddb.jpg","belongs_to_collection":null,"budget":132000000,"genres":[{"id":12,"name":"Adventure"},{"id":53,"name":"Thriller"},{"id":878,"name":"Science Fiction"}],"homepage":"","id":74,"imdb_id":"tt0407304","original_language":"en","original_title":"War of the Worlds","overview":"Ray Ferrier is a divorced dockworker and less-than-perfect father. Soon after his ex-wife and her new husband drop of his teenage son and young daughter for a rare weekend visit, a strange and powerful lightning storm touches down.","popularity":5.644492,"poster_path":"/xXMM9KY2eq1SDOQif9zO91YOBA8.jpg","production_companies":[{"name":"Paramount Pictures","id":4},{"name":"DreamWorks SKG","id":27},{"name":"Cruise/Wagner Productions","id":44},{"name":"Amblin Entertainment","id":56}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2005-06-23","revenue":591739379,"runtime":116,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"They're already here.","title":"War of the Worlds","video":false,"vote_average":6.1,"vote_count":2099} """
                                      ,"""  {"adult":false,"backdrop_path":"/bAlizRLmB0yJubWCwtJyofBfY0f.jpg","belongs_to_collection":null,"budget":70000000,"genres":[{"id":35,"name":"Comedy"},{"id":14,"name":"Fantasy"},{"id":878,"name":"Science Fiction"}],"homepage":"http://marsattacks.warnerbros.com/","id":75,"imdb_id":"tt0116996","original_language":"en","original_title":"Mars Attacks!","overview":"'We come in peace' is not what those green men from Mars mean when they invade our planet, armed with irresistible weapons and a cruel sense of humor.  This star studded cast must play victim to the alien’s fun and games in this comedy homage to science fiction films of the '50s and '60s.","popularity":4.612658,"poster_path":"/gaTuHICwavPUmqQzPZFEXKSRwsC.jpg","production_companies":[{"name":"Tim Burton Productions","id":8601}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1996-12-12","revenue":101371017,"runtime":106,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"fr","name":"Français"}],"status":"Released","tagline":"Nice planet. We'll take it!","title":"Mars Attacks!","video":false,"vote_average":6.1,"vote_count":1388} """
                                      ,"""  {"adult":false,"backdrop_path":"/x2M8mp6wSU4iFPECacHJkQuuvYx.jpg","belongs_to_collection":{"id":123800,"name":"Before... Collection","poster_path":"/giaxAC74fht0LVQ4WKVoDzLM2Iy.jpg","backdrop_path":"/wtNugZq8ZzBYwPIh3VoNUJdkBWG.jpg"},"budget":2500000,"genres":[{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],"homepage":"","id":76,"imdb_id":"tt0112471","original_language":"en","original_title":"Before Sunrise","overview":"A dialogue marathon of a film, this fairytale love story of an American boy and French girl. During a day and a night together in Vienna their two hearts collide.","popularity":3.379445,"poster_path":"/jsQy4ZbPHA8hE2O6QU05PpofI61.jpg","production_companies":[{"name":"Detour Film Production","id":98}],"production_countries":[{"iso_3166_1":"AT","name":"Austria"},{"iso_3166_1":"CH","name":"Switzerland"},{"iso_3166_1":"US","name":"United States of America"}],"release_date":"1995-01-27","revenue":5535405,"runtime":105,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"de","name":"Deutsch"},{"iso_639_1":"fr","name":"Français"}],"status":"Released","tagline":"Can the greatest romance of your life last only one night?","title":"Before Sunrise","video":false,"vote_average":7.7,"vote_count":887} """
                                      ,"""  {"adult":false,"backdrop_path":"/oBUznaSdjkY3HtQUzAxgdIZqh4w.jpg","belongs_to_collection":null,"budget":9000000,"genres":[{"id":9648,"name":"Mystery"},{"id":53,"name":"Thriller"}],"homepage":"http://www.otnemem.com/","id":77,"imdb_id":"tt0209144","original_language":"en","original_title":"Memento","overview":"Suffering short-term memory loss after a head injury, Leonard Shelby embarks on a grim quest to find the lowlife who murdered his wife in this gritty, complex thriller that packs more knots than a hangman's noose. To carry out his plan, Shelby snaps Polaroids of people and places, jotting down contextual notes on the backs of photos to aid in his search and jog his memory. He even tattoos his own body in a desperate bid to remember.","popularity":7.476823,"poster_path":"/fQMSaP88cf1nz4qwuNEEFtazuDM.jpg","production_companies":[{"name":"Summit Entertainment","id":491},{"name":"Newmarket Capital Group","id":506},{"name":"Team Todd","id":598},{"name":"I Remember Productions","id":34446}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2000-10-11","revenue":39723096,"runtime":113,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"Some memories are best forgotten.","title":"Memento","video":false,"vote_average":8.1,"vote_count":3640} """
                                      ,"""  {"adult":false,"backdrop_path":"/k36huckDH0v3LP1zo7maFt3mJC0.jpg","belongs_to_collection":{"id":422837,"name":"Blade Runner Collection","poster_path":"/foT46aJ7QPUFDl3CK8ArDl0JaZX.jpg","backdrop_path":"/xiOw9kLNfFPoe3j3J6nHqDTT1fu.jpg"},"budget":28000000,"genres":[{"id":878,"name":"Science Fiction"},{"id":18,"name":"Drama"},{"id":53,"name":"Thriller"}],"homepage":"http://www.warnerbros.com/blade-runner","id":78,"imdb_id":"tt0083658","original_language":"en","original_title":"Blade Runner","overview":"In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.","popularity":6.893046,"poster_path":"/p64TtbZGCElxQHpAMWmDHkWJlH2.jpg","production_companies":[{"name":"Shaw Brothers","id":5798},{"name":"Warner Bros.","id":6194},{"name":"The Ladd Company","id":7965}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"},{"iso_3166_1":"HK","name":"Hong Kong"},{"iso_3166_1":"GB","name":"United Kingdom"}],"release_date":"1982-06-25","revenue":33139618,"runtime":117,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"de","name":"Deutsch"},{"iso_639_1":"cn","name":"广州话 / 廣州話"},{"iso_639_1":"ja","name":"日本語"},{"iso_639_1":"hu","name":"Magyar"}],"status":"Released","tagline":"Man has made his match... now it's his problem.","title":"Blade Runner","video":false,"vote_average":7.9,"vote_count":3225} """
                                      ,"""  {"adult":false,"backdrop_path":"/xC9DRxpKgqJKDYLa9mkNa74eX4q.jpg","belongs_to_collection":null,"budget":31000000,"genres":[{"id":18,"name":"Drama"},{"id":12,"name":"Adventure"},{"id":28,"name":"Action"},{"id":36,"name":"History"}],"homepage":"","id":79,"imdb_id":"tt0299977","original_language":"zh","original_title":"英雄","overview":"One man defeated three assassins who sought to murder the most powerful warlord in pre-unified China.","popularity":3.527873,"poster_path":"/xkJnow23eDxwQXB0iIWAWkBF47y.jpg","production_companies":[{"name":"Beijing New Picture Film Co. Ltd.","id":724},{"name":"China Film Co-Production Corporation","id":2269}],"production_countries":[{"iso_3166_1":"CN","name":"China"}],"release_date":"2002-12-19","revenue":177394432,"runtime":99,"spoken_languages":[{"iso_639_1":"zh","name":"普通话"}],"status":"Released","tagline":"One man's strength will unite an empire.","title":"Hero","video":false,"vote_average":7.2,"vote_count":593} """
                                      ,"""  {"adult":false,"backdrop_path":"/2Kx2q1GOmYRjxmILEFIusMIGTUc.jpg","belongs_to_collection":{"id":123800,"name":"Before... Collection","poster_path":"/giaxAC74fht0LVQ4WKVoDzLM2Iy.jpg","backdrop_path":"/wtNugZq8ZzBYwPIh3VoNUJdkBWG.jpg"},"budget":2700000,"genres":[{"id":18,"name":"Drama"},{"id":10749,"name":"Romance"}],"homepage":"http://www.warnerbros.com/?site=beforesunset#/page=movies&pid=f-57b53b9e/BEFORE_SUNSET&asset=059437/Before_Sunset_-_Trailer_1A&type=video/","id":80,"imdb_id":"tt0381681","original_language":"en","original_title":"Before Sunset","overview":"Nine years ago two strangers met by chance and spent a night in Vienna that ended before sunrise. They are about to meet for the first time since. Now they have one afternoon to find out if they belong together.","popularity":1.78607,"poster_path":"/gycdE1ARByGQcK4fYR2mgpU6OO.jpg","production_companies":[{"name":"Castle Rock Entertainment","id":97},{"name":"Detour Film Production","id":98},{"name":"Warner Independent Pictures (WIP)","id":11509}],"production_countries":[{"iso_3166_1":"US","name":"United States of America"}],"release_date":"2004-02-10","revenue":15992615,"runtime":80,"spoken_languages":[{"iso_639_1":"en","name":"English"},{"iso_639_1":"fr","name":"Français"}],"status":"Released","tagline":"What if you had a second chance with the one that got away?","title":"Before Sunset","video":false,"vote_average":7.6,"vote_count":666} """
                                      ,"""  {"adult":false,"backdrop_path":"/qKIldRZ3jy3uGWdrNIt3P7QA5J3.jpg","belongs_to_collection":null,"budget":1000000,"genres":[{"id":12,"name":"Adventure"},{"id":16,"name":"Animation"},{"id":14,"name":"Fantasy"}],"homepage":"http://movies.disney.com/nausicaa-of-the-valley-of-the-wind","id":81,"imdb_id":"tt0087544","original_language":"ja","original_title":"風の谷のナウシカ","overview":"After a global war, the seaside kingdom known as the Valley Of The Wind remains one of the last strongholds on Earth untouched by a poisonous jungle and the powerful insects that guard it. Led by the courageous Princess Nausicaa, the people of the Valley engage in an epic struggle to restore the bond between humanity and Earth.","popularity":3.586111,"poster_path":"/hnYowHwLq0iUWriAHtiiCWsI2dP.jpg","production_companies":[{"name":"Topcraft","id":29}],"production_countries":[{"iso_3166_1":"JP","name":"Japan"}],"release_date":"1984-03-11","revenue":3301446,"runtime":117,"spoken_languages":[{"iso_639_1":"ja","name":"日本語"}],"status":"Released","tagline":"","title":"Nausicaä of the Valley of the Wind","video":false,"vote_average":7.7,"vote_count":733} """
  )
}
